"use client";

import React, { createContext, useContext, useState } from "react";

export type Language = "vi" | "en";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "vi",
  setLang: () => {},
  t: (key) => key,
});

export const translations: Record<Language, Record<string, string>> = {
  vi: {
    // Login page
    "app.title": "CTNC Report",
    "app.subtitle": "Hệ thống quản lý báo cáo dự án CTNC",
    "login.userId": "Email",
    "login.userId.placeholder": "VD: minh.hoangvan@ctnc.org.vn",
    "login.password": "Mật khẩu",
    "login.password.placeholder": "••••••••",
    "login.submit": "Đăng nhập",
    "login.loading": "Đang xác thực...",
    "login.error": "Email hoặc mật khẩu không đúng.",
    "login.forgotPassword": "Quên mật khẩu?",
    "login.signup": "Đăng ký tài khoản",
    "login.remember": "Ghi nhớ đăng nhập",
    // Forgot password modal
    "forgot.title": "Quên mật khẩu?",
    "forgot.desc": "Mật khẩu được quản lý bởi Admin hệ thống CTNC. Vui lòng liên hệ Admin để được đặt lại mật khẩu.",
    "forgot.contact": "Liên hệ Admin",
    "forgot.understood": "Đã hiểu",
    // Signup modal
    "signup.title": "Đăng ký tài khoản mới",
    "signup.desc": "Hệ thống CTNC Report sử dụng tài khoản được cấp phát bởi Admin. Người dùng không thể tự đăng ký.",
    "signup.request": "Yêu cầu cấp tài khoản",
    "signup.sendEmail": "Gửi email đến Admin với nội dung:",
    "signup.fullName": "Họ và tên đầy đủ",
    "signup.workEmail": "Email công việc",
    "signup.area": "Khu vực phụ trách",
    "signup.understood": "Đã hiểu",
    // Dashboard
    "dash.greeting": "Xin chào,",
    "dash.title": "Tổng quan dự án",
    "dash.subtitle": "Theo dõi tiến độ và các chỉ số quan trọng trong tháng 07/2026",
    "dash.newReport": "Tạo Báo Cáo Mới",
    "dash.stat.reports": "Báo cáo tháng này",
    "dash.stat.proposals": "Đề xuất đang xử lý",
    "dash.stat.activities": "Hoạt động hoàn thành",
    "dash.stat.issues": "Vấn đề cần hỗ trợ",
    "dash.deadlines": "Deadlines Sắp Tới",
    "dash.quickActions": "Hành động nhanh",
    "dash.action.proposal": "Cập nhật Proposal",
    "dash.action.issue": "Ghi nhận vấn đề (Issue)",
    "dash.action.settings": "Cấu hình Tài khoản",
    "dash.deadline.task1": "Nộp báo cáo quý 2",
    "dash.deadline.task2": "Hoàn thiện Proposal GCF",
    "dash.deadline.task3": "Survey đa dạng sinh học",
    "dash.deadline.site1": "Tay Hoa",
    "dash.deadline.site2": "Toàn dự án",
    "dash.deadline.site3": "Song Hinh",
    "dash.deadline.status1": "Gần đến hạn",
    "dash.deadline.status2": "Đang xử lý",
    "dash.deadline.status3": "Chưa bắt đầu",
    "dash.logout": "Đăng xuất",
    // Form
    "form.title": "Biểu mẫu Báo Cáo Tháng",
    "form.subtitle": "Hệ thống dữ liệu quan hệ (Relational DB) tối ưu",
    "form.step1": "Thông tin chung",
    "form.step2": "Báo cáo Khu vực",
    "form.step3": "Đề xuất & Báo cáo",
    "form.step4": "Thách thức & Ưu tiên",
    "form.step5": "Hoàn tất",
    "form.back": "Quay lại",
    "form.next": "Tiếp tục",
    "form.submit": "Gửi Báo Cáo",
    "form.submitting": "Đang gửi...",
    "form.success.title": "Thành công!",
    "form.success.desc": "Báo cáo đã được ghi nhận vào hệ thống.",
    "form.backDash": "Quay lại Dashboard",
    "form.addSite": "Thêm Site",
    "form.addProposal": "Thêm Đề xuất",
    "form.reportId": "Mã báo cáo",
    "form.month": "Tháng báo cáo (MM/YYYY)",
    "form.site": "Khu vực",
    "form.numActs": "Số hoạt động",
    "form.desc": "Hoạt động / mô tả",
    "form.activityNotes": "Hoạt động và ghi chú trong tháng",
    "form.keyActivities": "Hoạt động chính",
    "form.keyResults": "Kết quả",
    "form.difficulties": "Khó khăn, thách thức",
    "form.followUp": "Việc cần theo dõi",
    "form.results": "Kết quả chính, khó khăn, việc cần theo dõi",
    "form.plan": "Kế hoạch tháng tới",
    "form.relatedDocs": "Tài liệu liên quan",
    "form.addDoc": "Thêm link",
    "form.docLabel": "Mô tả ngắn",
    "form.propName": "Tên đề xuất",
    "form.propWriter": "Người viết",
    "form.propDonor": "Nhà tài trợ",
    "form.propStatus": "Trạng thái",
    "form.propDeadline": "Hạn chót",
    "form.propNote": "Ghi chú",
    "form.issueType": "Loại",
    "form.issueType.issue": "Vấn đề",
    "form.issueType.priority": "Ưu tiên tháng tới",
    "form.issuePic": "Người phụ trách",
    "form.issueDeadline": "Hạn chót",
    "form.issueDesc": "Mô tả",
    "form.addIssue": "Thêm mục",
    "form.saveDraft": "Lưu nháp",
    "form.noItems": "Chưa có mục nào.",
    "form.remove": "Xóa",
    "form.step.general": "Thông tin chung",
    "form.step.sites": "Hoạt động theo khu vực",
    "form.step.proposals": "Đề xuất (Proposals)",
    "form.step.reportsdata": "Báo cáo & cập nhật dữ liệu",
    "form.step.comms": "Truyền thông",
    "form.step.issues": "Vấn đề cần hỗ trợ",
    "form.step.priorities": "Ưu tiên tháng tới",
    "form.step.deadlines": "Deadline quan trọng",
    "form.step.review": "Xem lại & Gửi",
    "form.preparedBy": "Người chuẩn bị",
    "form.dateePrepared": "Ngày chuẩn bị",
    "form.addActivity": "Thêm hoạt động",
    "form.activityType": "Loại hoạt động",
    "form.activityDesc": "Mô tả ngắn",
    "form.numActsAuto": "Số hoạt động (tự đếm)",
    "form.photos": "Ảnh / tài liệu minh họa",
    "form.uploadPhoto": "Tải ảnh lên",
    "form.uploading": "Đang tải...",
    "form.photoCaption": "Chú thích ảnh",
    "form.addReportItem": "Thêm mục báo cáo",
    "form.itemName": "Tên báo cáo / bộ dữ liệu",
    "form.itemType": "Loại",
    "form.statusUpdate": "Tiến độ / cập nhật",
    "form.deadlineAction": "Hạn chót & hành động tiếp theo",
    "form.commChannel": "Kênh",
    "form.commCount": "Số lượng hoàn thành",
    "form.commThisMonth": "Diễn ra trong tháng",
    "form.commNextMonth": "Kế hoạch tháng tới",
    "form.actionNeeded": "Hành động / hỗ trợ cần thiết",
    "form.addPriority": "Thêm ưu tiên",
    "form.priorityNo": "Ưu tiên #",
    "form.plannedActivity": "Hoạt động dự kiến",
    "form.addDeadline": "Thêm deadline",
    "form.eventDate": "Ngày",
    "form.eventDesc": "Sự kiện / deadline",
    "form.siteDonor": "Khu vực / Donor",
    "form.reviewSummary": "Tóm tắt trước khi gửi",
    "nav.dashboard": "Tổng quan",
    "nav.reports": "Báo cáo",
    "nav.approve": "Duyệt báo cáo",
    "nav.members": "Thành viên",
    "nav.profile": "Hồ sơ cá nhân",
    "reports.title": "Báo cáo",
    "reports.subtitle": "Danh sách báo cáo tháng",
    "reports.col.id": "Mã BC",
    "reports.col.member": "Thành viên",
    "reports.col.month": "Tháng",
    "reports.col.acts": "HĐ",
    "reports.col.status": "Trạng thái",
    "reports.col.actions": "Thao tác",
    "reports.view": "Xem",
    "reports.edit": "Sửa",
    "reports.empty": "Chưa có báo cáo nào.",
    "reports.delete": "Xóa",
    "reports.deleteConfirm": "Xóa vĩnh viễn báo cáo này? Toàn bộ dữ liệu con (hoạt động, đề xuất, truyền thông...) sẽ bị xóa theo. Hành động này không thể hoàn tác.",
    "reports.deleteForbidden": "Bạn không có quyền xóa báo cáo này. Chỉ chủ báo cáo (khi còn ở trạng thái Nháp) hoặc Admin mới xóa được.",
    "status.draft": "Nháp",
    "status.submitted": "Đã nộp",
    "status.approved": "Đã duyệt",
    "status.returned": "Trả lại",
    "status.missing": "Chưa nộp",
    "approve.title": "Duyệt báo cáo",
    "approve.subtitle": "Báo cáo đã nộp đang chờ phê duyệt",
    "approve.empty": "Không có báo cáo chờ duyệt.",
    "approve.approve": "Duyệt",
    "approve.return": "Trả lại",
    "approve.confirmReturn": "Trả lại báo cáo này để yêu cầu chỉnh sửa?",
    "comments.title": "Bình luận & Trao đổi",
    "comments.empty": "Chưa có bình luận nào cho báo cáo này.",
    "comments.new": "Viết bình luận mới",
    "comments.placeholder": "Nhập nội dung bình luận cho báo cáo này...",
    "comments.visibility": "Ai có thể xem bình luận này?",
    "comments.visibilityAll": "Toàn bộ thành viên CTNC",
    "comments.visibilitySelected": "Chỉ định thành viên cụ thể",
    "comments.selectMembers": "Chọn thành viên được xem",
    "comments.post": "Đăng bình luận",
    "comments.reply": "Trả lời",
    "comments.replyPlaceholder": "Viết phản hồi...",
    "comments.send": "Gửi",
    "comments.cancel": "Hủy",
    "comments.managerOnly": "Chỉ Manager/Admin mới có thể mở bình luận mới. Bạn có thể trả lời các bình luận bên dưới.",
    "comments.visibleToAll": "Hiển thị: Toàn bộ CTNC",
    "comments.visibleToCount": "Hiển thị: {n} thành viên được chỉ định",
    "comments.selectAtLeastOne": "Vui lòng chọn ít nhất 1 thành viên.",
    "members.title": "Thành viên",
    "members.subtitle": "Quản lý tài khoản và phân quyền",
    "members.add": "Thêm thành viên",
    "members.col.id": "Mã",
    "members.col.name": "Họ tên",
    "members.col.role": "Vai trò",
    "members.col.email": "Email",
    "members.col.active": "Hoạt động",
    "members.save": "Lưu",
    "members.cancel": "Hủy",
    "members.password": "Mật khẩu",
        "members.newPassword": "Mật khẩu mới (để trống nếu không đổi)",
    "members.delete": "Xóa",
    "members.deleteConfirm": "Xóa vĩnh viễn thành viên này? Hành động này không thể hoàn tác.",
    "members.deleteSelfError": "Không thể tự xóa chính mình.",
    "members.adminOnlyNote": "Chỉ Admin mới có quyền đổi vai trò, vô hiệu hóa hoặc xóa thành viên.",
    "profile.title": "Hồ sơ cá nhân",
    "profile.subtitle": "Quản lý thông tin đăng nhập và hồ sơ của bạn",
    "profile.avatar": "Ảnh đại diện",
    "profile.changeAvatar": "Đổi ảnh đại diện",
    "profile.uploading": "Đang tải ảnh...",
    "profile.fullName": "Họ và tên",
    "profile.email": "Email đăng nhập",
    "profile.emailNote": "Liên hệ Admin nếu cần đổi email đăng nhập.",
    "profile.role": "Vai trò",
    "profile.saveInfo": "Lưu thông tin",
    "profile.changePassword": "Đổi mật khẩu",
    "profile.newPassword": "Mật khẩu mới",
    "profile.confirmPassword": "Nhập lại mật khẩu mới",
    "profile.passwordMismatch": "Mật khẩu nhập lại không khớp.",
    "profile.passwordTooShort": "Mật khẩu cần ít nhất 6 ký tự.",
    "profile.updatePassword": "Cập nhật mật khẩu",
    "profile.saved": "Đã lưu thành công.",
    "role.admin": "Quản trị",
    "role.manager": "Quản lý",
    "role.staff": "Cán bộ",
    "common.loading": "Đang tải…",
    "common.save": "Lưu",
    "common.cancel": "Hủy",
    "common.close": "Đóng",
    "login.wrongUser": "Sai email hoặc mật khẩu.",
    "dash.selectMonth": "Chọn tháng",
    "dash.export": "Xuất báo cáo",
    "dash.exportExcel": "Xuất Excel",
    "dash.exportWord": "Xuất Word",
    "dash.exportPdf": "Xuất PDF",
    "dash.exporting": "Đang tạo file...",
    "dash.completionRate": "Tỷ lệ hoàn thành",
    "dash.chartSiteTitle": "Hoạt động theo khu vực",
    "dash.chartTrendTitle": "Xu hướng 6 tháng gần nhất",
    "dash.chartProposalsTitle": "Thống kê đề xuất",
    "dash.chartDonorTitle": "Đề xuất theo nhà tài trợ",
    "dash.chartTypeTitle": "Hoạt động theo loại",
    "dash.chartCommsTitle": "Truyền thông theo kênh — 6 tháng",
    "dash.deadlinesTitle": "Deadline sắp tới",
    "dash.overdue": "Quá hạn",
    "dash.daysUnit": "ngày",
    "dash.stat.comms": "Sản phẩm truyền thông",
    "dash.issuesTitle": "Vấn đề cần hỗ trợ",
    "dash.prioritiesTitle": "Ưu tiên tháng tới",
    "dash.membersTitle": "Trạng thái nộp báo cáo theo thành viên",
    "dash.submitted": "đã nộp",
    "dash.noData": "Chưa có dữ liệu",
    "dash.trendReports": "Báo cáo đã nộp",
    "dash.trendActivities": "Tổng hoạt động",
    "dash.totalMembers": "Tổng thành viên",
    "dash.viewReport": "Xem báo cáo",
    "dash.subtitleShort": "Theo dõi tiến độ và các chỉ số quan trọng",
  },
  en: {
    // Login page
    "app.title": "CTNC Report",
    "app.subtitle": "CTNC Project Report Management System",
    "login.userId": "Email",
    "login.userId.placeholder": "E.g: minh.hoangvan@ctnc.org.vn",
    "login.password": "Password",
    "login.password.placeholder": "••••••••",
    "login.submit": "Sign In",
    "login.loading": "Authenticating...",
    "login.error": "Invalid email or password.",
    "login.forgotPassword": "Forgot password?",
    "login.signup": "Create account",
    "login.remember": "Remember me",
    // Forgot password modal
    "forgot.title": "Forgot Password?",
    "forgot.desc": "Passwords are managed by the CTNC System Administrator. Please contact the Admin to reset your password.",
    "forgot.contact": "Contact Admin",
    "forgot.understood": "Got it",
    // Signup modal
    "signup.title": "Create New Account",
    "signup.desc": "CTNC Report System accounts are issued by the Admin. Users cannot self-register.",
    "signup.request": "Request Account Access",
    "signup.sendEmail": "Send an email to Admin with:",
    "signup.fullName": "Full name",
    "signup.workEmail": "Work email",
    "signup.area": "Area of responsibility",
    "signup.understood": "Got it",
    // Dashboard
    "dash.greeting": "Hello,",
    "dash.title": "Project Overview",
    "dash.subtitle": "Track progress and key metrics for July 2026",
    "dash.newReport": "Create New Report",
    "dash.stat.reports": "Reports this month",
    "dash.stat.proposals": "Proposals in progress",
    "dash.stat.activities": "Activities completed",
    "dash.stat.issues": "Issues needing support",
    "dash.deadlines": "Upcoming Deadlines",
    "dash.quickActions": "Quick Actions",
    "dash.action.proposal": "Update Proposal",
    "dash.action.issue": "Log an Issue",
    "dash.action.settings": "Account Settings",
    "dash.deadline.task1": "Submit Q2 Report",
    "dash.deadline.task2": "Finalize GCF Proposal",
    "dash.deadline.task3": "Biodiversity Survey",
    "dash.deadline.site1": "Tay Hoa",
    "dash.deadline.site2": "All sites",
    "dash.deadline.site3": "Song Hinh",
    "dash.deadline.status1": "Due soon",
    "dash.deadline.status2": "In progress",
    "dash.deadline.status3": "Not started",
    "dash.logout": "Sign Out",
    // Form
    "form.title": "Monthly Report Form",
    "form.subtitle": "Optimized Relational Database structure",
    "form.step1": "General Info",
    "form.step2": "Site Report",
    "form.step3": "Proposals",
    "form.step4": "Challenges & Priorities",
    "form.step5": "Complete",
    "form.back": "Back",
    "form.next": "Continue",
    "form.submit": "Submit Report",
    "form.submitting": "Submitting...",
    "form.success.title": "Success!",
    "form.success.desc": "Your report has been recorded in the system.",
    "form.backDash": "Back to Dashboard",
    "form.addSite": "Add Site",
    "form.addProposal": "Add Proposal",
    "form.reportId": "Report ID",
    "form.month": "Reporting month (MM/YYYY)",
    "form.site": "Site",
    "form.numActs": "Number of activities",
    "form.desc": "Activities / description",
    "form.activityNotes": "Activities and key notes this month",
    "form.keyActivities": "Key activities",
    "form.keyResults": "Key results",
    "form.difficulties": "Difficulties, challenges",
    "form.followUp": "Follow-up",
    "form.results": "Key results, challenges or follow-up",
    "form.plan": "Plan for next month",
    "form.relatedDocs": "Related documents",
    "form.addDoc": "Add link",
    "form.docLabel": "Short label",
    "form.propName": "Proposal name",
    "form.propWriter": "Writer",
    "form.propDonor": "Donor",
    "form.propStatus": "Status",
    "form.propDeadline": "Deadline",
    "form.propNote": "Note",
    "form.issueType": "Type",
    "form.issueType.issue": "Issue",
    "form.issueType.priority": "Next month priority",
    "form.issuePic": "Person in charge",
    "form.issueDeadline": "Deadline",
    "form.issueDesc": "Description",
    "form.addIssue": "Add item",
    "form.saveDraft": "Save draft",
    "form.noItems": "No items yet.",
    "form.remove": "Remove",
    "form.step.general": "General information",
    "form.step.sites": "Activities by site",
    "form.step.proposals": "Proposals",
    "form.step.reportsdata": "Reports & data updates",
    "form.step.comms": "Communications",
    "form.step.issues": "Issues needing support",
    "form.step.priorities": "Priorities for next month",
    "form.step.deadlines": "Important deadlines",
    "form.step.review": "Review & submit",
    "form.preparedBy": "Prepared by",
    "form.dateePrepared": "Date prepared",
    "form.addActivity": "Add activity",
    "form.activityType": "Activity type",
    "form.activityDesc": "Short description",
    "form.numActsAuto": "Number of activities (auto-counted)",
    "form.photos": "Photos / supporting materials",
    "form.uploadPhoto": "Upload photo",
    "form.uploading": "Uploading...",
    "form.photoCaption": "Caption",
    "form.addReportItem": "Add report item",
    "form.itemName": "Report / dataset name",
    "form.itemType": "Type",
    "form.statusUpdate": "Status / progress",
    "form.deadlineAction": "Deadline & next action",
    "form.commChannel": "Channel",
    "form.commCount": "Number completed",
    "form.commThisMonth": "What happened this month",
    "form.commNextMonth": "Plan for next month",
    "form.actionNeeded": "Action or support needed",
    "form.addPriority": "Add priority",
    "form.priorityNo": "Priority #",
    "form.plannedActivity": "Planned activity",
    "form.addDeadline": "Add deadline",
    "form.eventDate": "Date",
    "form.eventDesc": "Event / deadline",
    "form.siteDonor": "Site / donor",
    "form.reviewSummary": "Summary before submitting",
    "nav.dashboard": "Dashboard",
    "nav.reports": "Reports",
    "nav.approve": "Approvals",
    "nav.members": "Members",
    "nav.profile": "My Profile",
    "reports.title": "Reports",
    "reports.subtitle": "Monthly report list",
    "reports.col.id": "Report ID",
    "reports.col.member": "Member",
    "reports.col.month": "Month",
    "reports.col.acts": "Acts",
    "reports.col.status": "Status",
    "reports.col.actions": "Actions",
    "reports.view": "View",
    "reports.edit": "Edit",
    "reports.empty": "No reports yet.",
    "reports.delete": "Delete",
    "reports.deleteConfirm": "Permanently delete this report? All child data (activities, proposals, communications...) will be deleted too. This cannot be undone.",
    "reports.deleteForbidden": "You don't have permission to delete this report. Only the owner (while still Draft) or an Admin can delete it.",
    "status.draft": "Draft",
    "status.submitted": "Submitted",
    "status.approved": "Approved",
    "status.returned": "Returned",
    "status.missing": "Not submitted",
    "approve.title": "Report Approvals",
    "approve.subtitle": "Submitted reports awaiting review",
    "approve.empty": "No reports awaiting approval.",
    "approve.approve": "Approve",
    "approve.return": "Return",
    "approve.confirmReturn": "Return this report for revision?",
    "comments.title": "Comments & Discussion",
    "comments.empty": "No comments yet on this report.",
    "comments.new": "Write a new comment",
    "comments.placeholder": "Write a comment on this report...",
    "comments.visibility": "Who can see this comment?",
    "comments.visibilityAll": "All CTNC members",
    "comments.visibilitySelected": "Specific members only",
    "comments.selectMembers": "Select members who can see it",
    "comments.post": "Post comment",
    "comments.reply": "Reply",
    "comments.replyPlaceholder": "Write a reply...",
    "comments.send": "Send",
    "comments.cancel": "Cancel",
    "comments.managerOnly": "Only Managers/Admins can start a new comment thread. You can reply to comments below.",
    "comments.visibleToAll": "Visible to: All CTNC",
    "comments.visibleToCount": "Visible to: {n} selected members",
    "comments.selectAtLeastOne": "Please select at least 1 member.",
    "members.title": "Members",
    "members.subtitle": "Manage accounts and roles",
    "members.add": "Add member",
    "members.col.id": "ID",
    "members.col.name": "Full name",
    "members.col.role": "Role",
    "members.col.email": "Email",
    "members.col.active": "Active",
    "members.save": "Save",
    "members.cancel": "Cancel",
    "members.password": "Password",
        "members.newPassword": "New password (leave blank to keep)",
    "members.delete": "Delete",
    "members.deleteConfirm": "Permanently delete this member? This cannot be undone.",
    "members.deleteSelfError": "You cannot delete your own account.",
    "members.adminOnlyNote": "Only Admins can change roles, deactivate, or delete members.",
    "profile.title": "My Profile",
    "profile.subtitle": "Manage your login and profile information",
    "profile.avatar": "Profile photo",
    "profile.changeAvatar": "Change photo",
    "profile.uploading": "Uploading...",
    "profile.fullName": "Full name",
    "profile.email": "Login email",
    "profile.emailNote": "Contact an Admin to change your login email.",
    "profile.role": "Role",
    "profile.saveInfo": "Save info",
    "profile.changePassword": "Change password",
    "profile.newPassword": "New password",
    "profile.confirmPassword": "Confirm new password",
    "profile.passwordMismatch": "Passwords do not match.",
    "profile.passwordTooShort": "Password must be at least 6 characters.",
    "profile.updatePassword": "Update password",
    "profile.saved": "Saved successfully.",
    "role.admin": "Admin",
    "role.manager": "Manager",
    "role.staff": "Staff",
    "common.loading": "Loading…",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.close": "Close",
    "login.wrongUser": "Invalid email or password.",
    "dash.selectMonth": "Select month",
    "dash.export": "Export report",
    "dash.exportExcel": "Export Excel",
    "dash.exportWord": "Export Word",
    "dash.exportPdf": "Export PDF",
    "dash.exporting": "Generating file...",
    "dash.completionRate": "Completion rate",
    "dash.chartSiteTitle": "Activities by site",
    "dash.chartTrendTitle": "Last 6 months trend",
    "dash.chartProposalsTitle": "Proposal statistics",
    "dash.chartDonorTitle": "Proposals by donor",
    "dash.chartTypeTitle": "Activities by type",
    "dash.chartCommsTitle": "Communications by channel — 6 months",
    "dash.deadlinesTitle": "Upcoming deadlines",
    "dash.overdue": "Overdue",
    "dash.daysUnit": "days",
    "dash.stat.comms": "Comms outputs",
    "dash.issuesTitle": "Issues needing support",
    "dash.prioritiesTitle": "Next month priorities",
    "dash.membersTitle": "Submission status by members",
    "dash.submitted": "submitted",
    "dash.noData": "No data yet",
    "dash.trendReports": "Reports submitted",
    "dash.trendActivities": "Total activities",
    "dash.totalMembers": "Total members",
    "dash.viewReport": "View report",
    "dash.subtitleShort": "Track progress and key metrics",
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    if (typeof window === "undefined") return "vi";
    const saved = window.localStorage.getItem("ctnc-lang");
    return saved === "vi" || saved === "en" ? saved : "vi";
  });

  const setLang = (l: Language) => {
    setLangState(l);
    localStorage.setItem("ctnc-lang", l);
  };

  const t = (key: string): string => {
    return translations[lang][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
